// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: index.proto

package indexproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CidEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	CreateTime    int64                  `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Refs          int32                  `protobuf:"varint,4,opt,name=refs,proto3" json:"refs,omitempty"`
	Version       uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CidEntry) Reset() {
	*x = CidEntry{}
	mi := &file_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CidEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CidEntry) ProtoMessage() {}

func (x *CidEntry) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CidEntry.ProtoReflect.Descriptor instead.
func (*CidEntry) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{0}
}

func (x *CidEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CidEntry) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *CidEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *CidEntry) GetRefs() int32 {
	if x != nil {
		return x.Refs
	}
	return 0
}

func (x *CidEntry) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CidList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cids          [][]byte               `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CidList) Reset() {
	*x = CidList{}
	mi := &file_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CidList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CidList) ProtoMessage() {}

func (x *CidList) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CidList.ProtoReflect.Descriptor instead.
func (*CidList) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{1}
}

func (x *CidList) GetCids() [][]byte {
	if x != nil {
		return x.Cids
	}
	return nil
}

type GroupEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	CreateTime    int64                  `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	CidCount      uint64                 `protobuf:"varint,5,opt,name=cidCount,proto3" json:"cidCount,omitempty"`
	SpaceIds      []string               `protobuf:"bytes,6,rep,name=spaceIds,proto3" json:"spaceIds,omitempty"`
	Limit         uint64                 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	AccountLimit  uint64                 `protobuf:"varint,8,opt,name=accountLimit,proto3" json:"accountLimit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupEntry) Reset() {
	*x = GroupEntry{}
	mi := &file_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEntry) ProtoMessage() {}

func (x *GroupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupEntry.ProtoReflect.Descriptor instead.
func (*GroupEntry) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{2}
}

func (x *GroupEntry) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupEntry) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GroupEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *GroupEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GroupEntry) GetCidCount() uint64 {
	if x != nil {
		return x.CidCount
	}
	return 0
}

func (x *GroupEntry) GetSpaceIds() []string {
	if x != nil {
		return x.SpaceIds
	}
	return nil
}

func (x *GroupEntry) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GroupEntry) GetAccountLimit() uint64 {
	if x != nil {
		return x.AccountLimit
	}
	return 0
}

type SpaceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	CreateTime    int64                  `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	FileCount     uint32                 `protobuf:"varint,5,opt,name=fileCount,proto3" json:"fileCount,omitempty"`
	CidCount      uint64                 `protobuf:"varint,6,opt,name=cidCount,proto3" json:"cidCount,omitempty"`
	Limit         uint64                 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceEntry) Reset() {
	*x = SpaceEntry{}
	mi := &file_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceEntry) ProtoMessage() {}

func (x *SpaceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceEntry.ProtoReflect.Descriptor instead.
func (*SpaceEntry) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{3}
}

func (x *SpaceEntry) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SpaceEntry) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *SpaceEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *SpaceEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SpaceEntry) GetFileCount() uint32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *SpaceEntry) GetCidCount() uint64 {
	if x != nil {
		return x.CidCount
	}
	return 0
}

func (x *SpaceEntry) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cids          []string               `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	CreateTime    int64                  `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,4,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{4}
}

func (x *FileEntry) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

func (x *FileEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FileEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_index_proto protoreflect.FileDescriptor

const file_index_proto_rawDesc = "" +
	"\n" +
	"\vindex.proto\x12\x0efileIndexProto\"\x8c\x01\n" +
	"\bCidEntry\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x1e\n" +
	"\n" +
	"createTime\x18\x02 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x03 \x01(\x03R\n" +
	"updateTime\x12\x12\n" +
	"\x04refs\x18\x04 \x01(\x05R\x04refs\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\"\x1d\n" +
	"\aCidList\x12\x12\n" +
	"\x04cids\x18\x01 \x03(\fR\x04cids\"\xec\x01\n" +
	"\n" +
	"GroupEntry\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x02 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x03 \x01(\x03R\n" +
	"updateTime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x1a\n" +
	"\bcidCount\x18\x05 \x01(\x04R\bcidCount\x12\x1a\n" +
	"\bspaceIds\x18\x06 \x03(\tR\bspaceIds\x12\x14\n" +
	"\x05limit\x18\a \x01(\x04R\x05limit\x12\"\n" +
	"\faccountLimit\x18\b \x01(\x04R\faccountLimit\"\xca\x01\n" +
	"\n" +
	"SpaceEntry\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x02 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x03 \x01(\x03R\n" +
	"updateTime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x1c\n" +
	"\tfileCount\x18\x05 \x01(\rR\tfileCount\x12\x1a\n" +
	"\bcidCount\x18\x06 \x01(\x04R\bcidCount\x12\x14\n" +
	"\x05limit\x18\a \x01(\x04R\x05limit\"s\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04cids\x18\x01 \x03(\tR\x04cids\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1e\n" +
	"\n" +
	"createTime\x18\x03 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x04 \x01(\x03R\n" +
	"updateTimeB\x12Z\x10index/indexprotob\x06proto3"

var (
	file_index_proto_rawDescOnce sync.Once
	file_index_proto_rawDescData []byte
)

func file_index_proto_rawDescGZIP() []byte {
	file_index_proto_rawDescOnce.Do(func() {
		file_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_index_proto_rawDesc), len(file_index_proto_rawDesc)))
	})
	return file_index_proto_rawDescData
}

var file_index_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_index_proto_goTypes = []any{
	(*CidEntry)(nil),   // 0: fileIndexProto.CidEntry
	(*CidList)(nil),    // 1: fileIndexProto.CidList
	(*GroupEntry)(nil), // 2: fileIndexProto.GroupEntry
	(*SpaceEntry)(nil), // 3: fileIndexProto.SpaceEntry
	(*FileEntry)(nil),  // 4: fileIndexProto.FileEntry
}
var file_index_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_index_proto_init() }
func file_index_proto_init() {
	if File_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_index_proto_rawDesc), len(file_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_index_proto_goTypes,
		DependencyIndexes: file_index_proto_depIdxs,
		MessageInfos:      file_index_proto_msgTypes,
	}.Build()
	File_index_proto = out.File
	file_index_proto_goTypes = nil
	file_index_proto_depIdxs = nil
}
