// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync-filenode/index (interfaces: Index)
//
// Generated by this command:
//
//	mockgen -destination mock_index/mock_index.go github.com/anyproto/any-sync-filenode/index Index
//

// Package mock_index is a generated GoMock package.
package mock_index

import (
	context "context"
	reflect "reflect"

	index "github.com/anyproto/any-sync-filenode/index"
	app "github.com/anyproto/any-sync/app"
	blocks "github.com/ipfs/go-block-format"
	cid "github.com/ipfs/go-cid"
	gomock "go.uber.org/mock/gomock"
)

// MockIndex is a mock of Index interface.
type MockIndex struct {
	ctrl     *gomock.Controller
	recorder *MockIndexMockRecorder
	isgomock struct{}
}

// MockIndexMockRecorder is the mock recorder for MockIndex.
type MockIndexMockRecorder struct {
	mock *MockIndex
}

// NewMockIndex creates a new mock instance.
func NewMockIndex(ctrl *gomock.Controller) *MockIndex {
	mock := &MockIndex{ctrl: ctrl}
	mock.recorder = &MockIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndex) EXPECT() *MockIndexMockRecorder {
	return m.recorder
}

// BlocksAdd mocks base method.
func (m *MockIndex) BlocksAdd(ctx context.Context, bs []blocks.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlocksAdd", ctx, bs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlocksAdd indicates an expected call of BlocksAdd.
func (mr *MockIndexMockRecorder) BlocksAdd(ctx, bs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlocksAdd", reflect.TypeOf((*MockIndex)(nil).BlocksAdd), ctx, bs)
}

// BlocksGetNonExistent mocks base method.
func (m *MockIndex) BlocksGetNonExistent(ctx context.Context, bs []blocks.Block) ([]blocks.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlocksGetNonExistent", ctx, bs)
	ret0, _ := ret[0].([]blocks.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlocksGetNonExistent indicates an expected call of BlocksGetNonExistent.
func (mr *MockIndexMockRecorder) BlocksGetNonExistent(ctx, bs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlocksGetNonExistent", reflect.TypeOf((*MockIndex)(nil).BlocksGetNonExistent), ctx, bs)
}

// BlocksLock mocks base method.
func (m *MockIndex) BlocksLock(ctx context.Context, bs []blocks.Block) (func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlocksLock", ctx, bs)
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlocksLock indicates an expected call of BlocksLock.
func (mr *MockIndexMockRecorder) BlocksLock(ctx, bs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlocksLock", reflect.TypeOf((*MockIndex)(nil).BlocksLock), ctx, bs)
}

// Check mocks base method.
func (m *MockIndex) Check(ctx context.Context, key index.Key, doFix bool) ([]index.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, key, doFix)
	ret0, _ := ret[0].([]index.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockIndexMockRecorder) Check(ctx, key, doFix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockIndex)(nil).Check), ctx, key, doFix)
}

// CheckDeletedSpaces mocks base method.
func (m *MockIndex) CheckDeletedSpaces(ctx context.Context, key index.Key, resolve func([]string) ([]string, error), doFix bool) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDeletedSpaces", ctx, key, resolve, doFix)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDeletedSpaces indicates an expected call of CheckDeletedSpaces.
func (mr *MockIndexMockRecorder) CheckDeletedSpaces(ctx, key, resolve, doFix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDeletedSpaces", reflect.TypeOf((*MockIndex)(nil).CheckDeletedSpaces), ctx, key, resolve, doFix)
}

// CheckKey mocks base method.
func (m *MockIndex) CheckKey(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckKey", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckKey indicates an expected call of CheckKey.
func (mr *MockIndexMockRecorder) CheckKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckKey", reflect.TypeOf((*MockIndex)(nil).CheckKey), ctx, key)
}

// CheckLimits mocks base method.
func (m *MockIndex) CheckLimits(ctx context.Context, key index.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLimits", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckLimits indicates an expected call of CheckLimits.
func (mr *MockIndexMockRecorder) CheckLimits(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLimits", reflect.TypeOf((*MockIndex)(nil).CheckLimits), ctx, key)
}

// CheckOwnership mocks base method.
func (m *MockIndex) CheckOwnership(ctx context.Context, key index.Key, oldIdentity string, aclRecordIndex int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOwnership", ctx, key, oldIdentity, aclRecordIndex)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckOwnership indicates an expected call of CheckOwnership.
func (mr *MockIndexMockRecorder) CheckOwnership(ctx, key, oldIdentity, aclRecordIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOwnership", reflect.TypeOf((*MockIndex)(nil).CheckOwnership), ctx, key, oldIdentity, aclRecordIndex)
}

// CidEntries mocks base method.
func (m *MockIndex) CidEntries(ctx context.Context, cids []cid.Cid) (*index.CidEntries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CidEntries", ctx, cids)
	ret0, _ := ret[0].(*index.CidEntries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CidEntries indicates an expected call of CidEntries.
func (mr *MockIndexMockRecorder) CidEntries(ctx, cids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CidEntries", reflect.TypeOf((*MockIndex)(nil).CidEntries), ctx, cids)
}

// CidEntriesByBlocks mocks base method.
func (m *MockIndex) CidEntriesByBlocks(ctx context.Context, bs []blocks.Block) (*index.CidEntries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CidEntriesByBlocks", ctx, bs)
	ret0, _ := ret[0].(*index.CidEntries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CidEntriesByBlocks indicates an expected call of CidEntriesByBlocks.
func (mr *MockIndexMockRecorder) CidEntriesByBlocks(ctx, bs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CidEntriesByBlocks", reflect.TypeOf((*MockIndex)(nil).CidEntriesByBlocks), ctx, bs)
}

// CidExists mocks base method.
func (m *MockIndex) CidExists(ctx context.Context, c cid.Cid) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CidExists", ctx, c)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CidExists indicates an expected call of CidExists.
func (mr *MockIndexMockRecorder) CidExists(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CidExists", reflect.TypeOf((*MockIndex)(nil).CidExists), ctx, c)
}

// CidExistsInSpace mocks base method.
func (m *MockIndex) CidExistsInSpace(ctx context.Context, key index.Key, cids []cid.Cid) ([]cid.Cid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CidExistsInSpace", ctx, key, cids)
	ret0, _ := ret[0].([]cid.Cid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CidExistsInSpace indicates an expected call of CidExistsInSpace.
func (mr *MockIndexMockRecorder) CidExistsInSpace(ctx, key, cids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CidExistsInSpace", reflect.TypeOf((*MockIndex)(nil).CidExistsInSpace), ctx, key, cids)
}

// Close mocks base method.
func (m *MockIndex) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIndexMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIndex)(nil).Close), ctx)
}

// FileBind mocks base method.
func (m *MockIndex) FileBind(ctx context.Context, key index.Key, fileId string, cidEntries *index.CidEntries) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileBind", ctx, key, fileId, cidEntries)
	ret0, _ := ret[0].(error)
	return ret0
}

// FileBind indicates an expected call of FileBind.
func (mr *MockIndexMockRecorder) FileBind(ctx, key, fileId, cidEntries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileBind", reflect.TypeOf((*MockIndex)(nil).FileBind), ctx, key, fileId, cidEntries)
}

// FileInfo mocks base method.
func (m *MockIndex) FileInfo(ctx context.Context, key index.Key, fileIds ...string) ([]index.FileInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range fileIds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FileInfo", varargs...)
	ret0, _ := ret[0].([]index.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileInfo indicates an expected call of FileInfo.
func (mr *MockIndexMockRecorder) FileInfo(ctx, key any, fileIds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, fileIds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileInfo", reflect.TypeOf((*MockIndex)(nil).FileInfo), varargs...)
}

// FileUnbind mocks base method.
func (m *MockIndex) FileUnbind(ctx context.Context, kye index.Key, fileIds ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, kye}
	for _, a := range fileIds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FileUnbind", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FileUnbind indicates an expected call of FileUnbind.
func (mr *MockIndexMockRecorder) FileUnbind(ctx, kye any, fileIds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, kye}, fileIds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileUnbind", reflect.TypeOf((*MockIndex)(nil).FileUnbind), varargs...)
}

// FilesList mocks base method.
func (m *MockIndex) FilesList(ctx context.Context, key index.Key) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilesList", ctx, key)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilesList indicates an expected call of FilesList.
func (mr *MockIndexMockRecorder) FilesList(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesList", reflect.TypeOf((*MockIndex)(nil).FilesList), ctx, key)
}

// GroupInfo mocks base method.
func (m *MockIndex) GroupInfo(ctx context.Context, groupId string) (index.GroupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupInfo", ctx, groupId)
	ret0, _ := ret[0].(index.GroupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupInfo indicates an expected call of GroupInfo.
func (mr *MockIndexMockRecorder) GroupInfo(ctx, groupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupInfo", reflect.TypeOf((*MockIndex)(nil).GroupInfo), ctx, groupId)
}

// Init mocks base method.
func (m *MockIndex) Init(a *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockIndexMockRecorder) Init(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockIndex)(nil).Init), a)
}

// MarkSpaceAsDeleted mocks base method.
func (m *MockIndex) MarkSpaceAsDeleted(ctx context.Context, key index.Key) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSpaceAsDeleted", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkSpaceAsDeleted indicates an expected call of MarkSpaceAsDeleted.
func (mr *MockIndexMockRecorder) MarkSpaceAsDeleted(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSpaceAsDeleted", reflect.TypeOf((*MockIndex)(nil).MarkSpaceAsDeleted), ctx, key)
}

// Migrate mocks base method.
func (m *MockIndex) Migrate(ctx context.Context, key index.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockIndexMockRecorder) Migrate(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockIndex)(nil).Migrate), ctx, key)
}

// Name mocks base method.
func (m *MockIndex) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockIndexMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockIndex)(nil).Name))
}

// OnBlockUploaded mocks base method.
func (m *MockIndex) OnBlockUploaded(ctx context.Context, bs ...blocks.Block) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range bs {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "OnBlockUploaded", varargs...)
}

// OnBlockUploaded indicates an expected call of OnBlockUploaded.
func (mr *MockIndexMockRecorder) OnBlockUploaded(ctx any, bs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, bs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBlockUploaded", reflect.TypeOf((*MockIndex)(nil).OnBlockUploaded), varargs...)
}

// Run mocks base method.
func (m *MockIndex) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockIndexMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIndex)(nil).Run), ctx)
}

// SetGroupLimit mocks base method.
func (m *MockIndex) SetGroupLimit(ctx context.Context, groupId string, limit uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGroupLimit", ctx, groupId, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGroupLimit indicates an expected call of SetGroupLimit.
func (mr *MockIndexMockRecorder) SetGroupLimit(ctx, groupId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGroupLimit", reflect.TypeOf((*MockIndex)(nil).SetGroupLimit), ctx, groupId, limit)
}

// SetSpaceLimit mocks base method.
func (m *MockIndex) SetSpaceLimit(ctx context.Context, key index.Key, limit uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSpaceLimit", ctx, key, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSpaceLimit indicates an expected call of SetSpaceLimit.
func (mr *MockIndexMockRecorder) SetSpaceLimit(ctx, key, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSpaceLimit", reflect.TypeOf((*MockIndex)(nil).SetSpaceLimit), ctx, key, limit)
}

// SpaceDelete mocks base method.
func (m *MockIndex) SpaceDelete(ctx context.Context, key index.Key) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpaceDelete", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpaceDelete indicates an expected call of SpaceDelete.
func (mr *MockIndexMockRecorder) SpaceDelete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpaceDelete", reflect.TypeOf((*MockIndex)(nil).SpaceDelete), ctx, key)
}

// SpaceInfo mocks base method.
func (m *MockIndex) SpaceInfo(ctx context.Context, key index.Key) (index.SpaceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpaceInfo", ctx, key)
	ret0, _ := ret[0].(index.SpaceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpaceInfo indicates an expected call of SpaceInfo.
func (mr *MockIndexMockRecorder) SpaceInfo(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpaceInfo", reflect.TypeOf((*MockIndex)(nil).SpaceInfo), ctx, key)
}

// WaitCidExists mocks base method.
func (m *MockIndex) WaitCidExists(ctx context.Context, c cid.Cid) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitCidExists", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitCidExists indicates an expected call of WaitCidExists.
func (mr *MockIndexMockRecorder) WaitCidExists(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitCidExists", reflect.TypeOf((*MockIndex)(nil).WaitCidExists), ctx, c)
}
